config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:passwords]
  root to: "games#index"
  resources :games, only: [:index, :new, :create, :edit, :update]
  get "games/:game_name", to: "games#show", as: :show_game
  get "about", to: "games#about", as: :about
  resources :images, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  with_options presence: true, uniqueness: { case_sensitive: true } do
    validates :display_name
    validates :game_name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username, presence: true, uniqueness: { case_sensitive: true }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, password_length: 4..128

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    update_attrs = [:password, :password_confirmation, :current_password, :username]
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: update_attrs)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :redirect_ileligible_user, only: [:new, :create, :edit, :update]
  before_action :find_game, only: [:edit, :update]

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if current_user.admin && @game.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @game = Game.where(game_name: params[:game_name])
    @nums1000 = create_array(1, 1000)
    @nums50 = create_array(1, 50)
  end

  def edit
  end

  def update
    if @game.update(game_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def about
  end

  private

  def redirect_ileligible_user
    redirect_to root_path unless user_signed_in? && current_user.admin
  end

  def game_params
    params.require(:game).permit(:image_url, :display_name, :game_name, :description)
  end

  def find_game
    @game = Game.find(params[:id])
  end

  def create_array(i, j)
    array = []
    (j - i + 1).times do |k|
      array << k + i
    end
    array
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    redirect_to root_path unless user_signed_in? && current_user.id == 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true )do |f| %>

  <div class="field">
    <%= f.label :display_name %><br />
    <%= f.text_field :display_name %>
  </div>

  <div class="field">
    <%= f.label :game_name %><br />
    <%= f.text_field :game_name %>
  </div>

  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>

<% end %>

app/views/games/_game.html.erb
<%= link_to show_game_path(game.game_name) do %>
  <div class="index-game">
    <h3 class="game-title"><%= game.display_name %></h3>
    <div class="game-image-div">
      <%= image_tag game.image_url, class:"game-image" %><br />
    </div>
    <%= simple_format(game.description, class:"game-description")%>
    <% if user_signed_in? && current_user.id == 1 %>
      <%= link_to "編集", edit_game_path(game.id) %><br />
    <% end %>
  </div>
<% end %>

app/views/games/about.html.erb
<% breadcrumb :about %>
<div class="about-wrapper">
  <h1>このサイトの方針</h1>
  <div class="about-contents">
    <h3>シンプルなゲームはシンプルに</h3>
    <div class="about-content">
      <p>装飾は最低限に</p>
      <p>できるかぎりストレスレスに</p>
      <p>ゲームが複雑になる機能は省く</p>
      <p>不快な広告は表示しない</p>
      <p>ユーザー登録しなくても遊べる</p>
      <p>ブラウザで気軽に遊べる</p>
    </div>
    <br><h3>作者自己紹介</h3>
    <div class="about-content">
      <p>名前：LynxLevin（リンクスルヴァン）</p>
      <p>年齢：30代前半</p>
      <p>職業：エンジニア目指して勉強中</p>
      <p>趣味：ワイン、写真、コーヒー</p>
      <p>性格：おっちょこちょい</p>
      <p>ブログ：<%= link_to "LynxLevinブログ","https://lynx-levin.hateblo.jp/", class:"about-blog-link" %></p>
      <p></p>
    </div>
    <br><h3>このサイトのプログラミング言語</h3>
    <div class="about-content">
      <p>Ruby on Rails, HTML, CSS, JavaScript</p>
    </div>
  </div>
  <br>
  <fieldset class="message-fieldset about-message">
    <legend class="message-legend"><h3>作者の思い</h3></legend>
    <p>僕は小さな頃からゲームっ子で、いつもゲームばかりしていました。
    当時のゲームはすごくワクワクする特別なもので、
    お年玉をもらうとどのゲームを買おうか、悩んで過ごす時間は楽しくて仕方がありませんでした。</p>
    <p>しかし、僕が生まれてから３０年と少しの間にゲームは大きな進化を遂げ、
    グラフィックもシステムもどんどん複雑になり、いつまでもクリアする（終わる）ことなく遊び続けられるようになりました。</p>
    <p>そして、ゲームの進化に比例するように、僕のゲームへの距離感も大きくなっていきました。</p>
    <p>昔、ゲームへ感じていたあのワクワク感はどこへ消えてしまったのだろう？</p>

    <p>シンプルなゲームはシンプルに遊びたい</p>
    <p>そういう人のためにゲームを作っていきたいと思っています。</p>
    <p>まだまだ駆け出しなので、満足に遊べるゲームを作れるまで、時間はかかってしまうかもしれませんが、
    疲れる時代に気軽にほっと一息つけるような、そんなゲームをいっぱい作れるよう、頑張っていきます。</p>
  </fieldset>
</div>

app/views/games/edit.html.erb
<% breadcrumb :edit_game %>
<%= render partial: "form", locals: { game: @game } %>

app/views/games/index.html.erb
<div class="main-wrapper">
  <div class="index-wrapper">
    <% if user_signed_in? %>
      <h3><%= "#{current_user.username}さん、いらっしゃい!" %></h3>
    <% end %>
    <div class="index-title">
      <h1>LynxLevin's Game Land</h1>
      <p><%= link_to "シンプルなゲームをシンプルに遊べるサイト", about_path %>を目指します</p>
    </div>
    <div class="index-games">
      <%= render partial: "game", collection: @games %>
    </div>
  </div>
  <footer>
    <div class="footer-left">
      <%= link_to "このサイトの思い", about_path %>
    </div>
    <div class="footer-right">
      <%= link_to "LynxLevinブログ","https://lynx-levin.hateblo.jp/" %>
    </div>
  </footer>
</div>

app/views/games/new.html.erb
<% breadcrumb :new_game %>
<%= render partial: "form", locals: { game: @game } %>

app/views/games/show.html.erb
<% breadcrumb :show_game, @game %>
<div id="game-wrapper">
  <div id="left-wrapper">
    <div id="top-btn-wrapper" style="display: none;">
      <button id="restart-game">RESTART</button>
      <p id="timer">00:00:00</p>
    </div>
    <span id="show-settings">設定を表示する</span>
    <input type="checkbox" name="checkbox" id="show-settings-check">
    <div id="inputs-wrapper" style="display: none;">
      <div id="difficulty-btns-wrapper" style="display: none;">
        <button class="difficulty-btn" id="difficulty1">EASY</button>
        <button class="difficulty-btn" id="difficulty2">MEDIUM</button>
        <button class="difficulty-btn" id="difficulty3">HARD</button>
      </div>
      <div id="select-boxes-wrapper" style="display: none;">
        <div class="select" id="select1-div">
          <select id="select1" class="select-tag">
            <%= options_for_select(@nums50) %>
          </select>
          <p id="select1-message" class="select-message"></p>
        </div>
        <div class="select" id="select2-div">
          <select id="select2" class="select-tag">
            <%= options_for_select(@nums1000) %>
          </select>
          <p id="select2-message" class="select-message"></p>
        </div>
      </div>
      <p id="input-info"></p>
    </div>
    <div id="game-btn-wrapper" style="display: none;">
      <button id="helper-btn" ></button><p id="helper-btn-message"></p>
      <div class="game-btn-div">
        <button id="game-btn1"></button>
        <p class="game-btn-text" id="game-btn-text1"></p>
      </div>
      <div class="game-btn-div">
        <button id="game-btn2"></button>
        <p class="game-btn-text" id="game-btn-text2"></p>
      </div>
    </div>
    <div id="game-info-wrapper" style="display: none;">
      <h3 id="info1"></h3>
      <h3 id="info2"></h3>
    </div>
  </div>
  <div id="center-wrapper">
    <button id="solver-btn">solve</button>
    <button id="fillAcorns">fillAcorns</button>
    <button id="fillNumbersAlreadyDone">fillNumbersAlreadyDone</button>
    <div class="board-div">
      <table id="board"></table>
      <div id="clear-image" style="display: none;"></div>
    </div>
    <p id="clear-message"></p>
  </div>
</div>

app/views/images/index.html.erb
<% breadcrumb :images %>
<%= image_tag '1tictactoe.png', class:"image-storage" %>
<%= image_tag '215puzzle.png', class:"image-storage" %>
<%= image_tag '3minesweeper.png', class:"image-storage" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>llGameLand</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
      <%= render "shared/header" %>
      <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<header>
  <div class="header-left">
    <%= breadcrumbs separator: "＞" %>
  </div>
  <div class="header-right">
    <% if user_signed_in? %>
      <%= link_to "マイページ", edit_user_registration_path, class:"header-content" %>
      <%= link_to "ログアウト", destroy_user_session_path, method: "DELETE", class:"header-content" %>
    <% else %>
      <%= link_to "ログイン", new_user_session_path, class:"header-content" %>
      <%= link_to "新規登録", new_user_registration_path, class:"header-content" %>
    <% end %>
    <% if user_signed_in? && current_user.admin %>
      <%= link_to "ゲーム登録", new_game_path, class:"header-content" %>
      <%= link_to "ゲーム画像", images_path, class:"header-content" %>
    <% end %>
  </div>
</header>

app/views/top/index.html.erb
<% if user_signed_in? %>
  <h3><%= "Hello, #{current_user.username}!" %></h3>
<% end %>
<h1>LynxLevin's Game Land</h1>
<% if user_signed_in? %>
  <%= link_to "マイページ", edit_user_registration_path %><br>
  <%= link_to "ログアウト", destroy_user_session_path, method: "DELETE" %><br>
<% else %>
  <%= link_to "ログイン", new_user_session_path %><br>
  <%= link_to "新規登録", new_user_registration_path %><br>
<% end %>
<% if user_signed_in? && current_user.id == 1 %>
  <%= link_to "ゲーム登録", new_game_path %><br>
<% end %>